[CmdletBinding()]
param(
    [string]$RpcUrl = $env:ARBITRUM_SEPOLIA_RPC_URL,
    [string]$PrivateKey = $env:DEPLOYER_PRIVATE_KEY,
    [string]$DeploymentFile = 'deployments/exploration-arbitrum-sepolia.json',
    [object]$Runs = 3,
    [object]$GasLimit = 1000000,
    [string]$OutputFile = 'deployments/exploration-arbitrum-sepolia-lifecycle-results.json'
)
$ErrorActionPreference='Stop'
if ([string]::IsNullOrWhiteSpace($RpcUrl)) { throw 'ARBITRUM_SEPOLIA_RPC_URL is required.' }
if ([string]::IsNullOrWhiteSpace($PrivateKey)) { throw 'DEPLOYER_PRIVATE_KEY is required.' }
try { $runCount = [int](@($Runs)[0]); $gasLimitValue = [int](@($GasLimit)[0]) }
catch { throw 'Runs and GasLimit must each be a single integer value.' }
if ($runCount -lt 1) { throw 'Runs must be at least 1.' }
if ($gasLimitValue -lt 300000) { throw 'GasLimit must be at least 300000.' }
$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path; $deploymentPath=Join-Path $repoRoot $DeploymentFile; $outputPath=Join-Path $repoRoot $OutputFile
if (-not (Test-Path -LiteralPath $deploymentPath)) { throw "Deployment metadata not found: $deploymentPath" }
$deployment=Get-Content -LiteralPath $deploymentPath -Raw | ConvertFrom-Json
if ([int64]$deployment.chainId -ne 421614) { throw 'Deployment file is not Arbitrum Sepolia metadata.' }
$pool=[string]$deployment.contracts.LendingPool; $weth=[string]$deployment.contracts.MockWETH; $dai=[string]$deployment.contracts.MockDAI

function Convert-RpcQuantity([object]$Value) { $text=([string]$Value).Trim(); if ($text -notmatch '^(?<token>0[xX][0-9a-fA-F]+|\d+)') { throw "Invalid RPC quantity: $text" }; $token=$Matches['token']; if ($token -match '^0[xX]') { return [System.Numerics.BigInteger]::Parse("0$($token.Substring(2))",[Globalization.NumberStyles]::AllowHexSpecifier,[Globalization.CultureInfo]::InvariantCulture) }; return [System.Numerics.BigInteger]::Parse($token,[Globalization.CultureInfo]::InvariantCulture) }
function Invoke-CastJson([string[]]$Arguments) { $raw=& cast @Arguments --json; if($LASTEXITCODE -ne 0){throw "cast failed: $($Arguments -join ' ')"}; $parsed=($raw -join "`n")|ConvertFrom-Json; if($parsed.PSObject.Properties.Name -contains 'data'){if($parsed.success -ne $true){throw 'cast returned an RPC error.'};return $parsed.data};return $parsed }
function Get-Uint([string]$Address,[string]$Signature,[string]$Argument=$null) { $callArgs=@('call',$Address,$Signature);if($null -ne $Argument){$callArgs+=$Argument};$callArgs+=@('--rpc-url',$RpcUrl);$value=(& cast @callArgs).Trim();if($LASTEXITCODE -ne 0){throw "cast call failed: $Signature"};return [string](Convert-RpcQuantity $value) }
function Get-Snapshot([string]$Label) { $actor=(& cast wallet address --private-key $PrivateKey).Trim();$latest=Invoke-CastJson @('block','latest','--rpc-url',$RpcUrl);$supplied=Get-Uint $pool 'totalDaiSupplied()(uint256)';$borrowed=Get-Uint $pool 'totalDaiBorrowed()(uint256)';$reserves=Get-Uint $pool 'totalReserves()(uint256)';$poolDai=Get-Uint $dai 'balanceOf(address)(uint256)' $pool;$expected=[System.Numerics.BigInteger]::Parse($supplied)-[System.Numerics.BigInteger]::Parse($borrowed)+[System.Numerics.BigInteger]::Parse($reserves);return [ordered]@{label=$Label;observedAtUtc=(Get-Date).ToUniversalTime().ToString('o');actor=$actor;blockNumber=[string](Convert-RpcQuantity ((& cast block-number --rpc-url $RpcUrl).Trim()));blockTimestamp=[string](Convert-RpcQuantity $latest.timestamp);principalDebt=Get-Uint $pool 'principalDebt(address)(uint256)' $actor;borrowIndex=Get-Uint $pool 'borrowIndex()(uint256)';supplyIndex=Get-Uint $pool 'supplyIndex()(uint256)';collateralBalance=Get-Uint $pool 'collateralBalance(address)(uint256)' $actor;totalDaiSupplied=$supplied;totalDaiBorrowed=$borrowed;totalReserves=$reserves;healthFactor=Get-Uint $pool 'healthFactor(address)(uint256)' $actor;poolDaiBalance=$poolDai;accountingIdentityHolds=([System.Numerics.BigInteger]::Parse($poolDai)-eq $expected)} }
function Invoke-Lifecycle() { $args=@('script','script/ExplorationLifecycle.s.sol:ExplorationLifecycle','--sig','run(address,address,address)',$pool,$weth,$dai,'--rpc-url',$RpcUrl,'--private-key',$PrivateKey,'--broadcast','--slow','--gas-limit',[string]$gasLimitValue);Push-Location $repoRoot;try{& forge @args;if($LASTEXITCODE -ne 0){throw 'Arbitrum lifecycle forge script failed.'}}finally{Pop-Location} }
function Get-Records([object]$RunNumber) { $runValue=[int]$RunNumber; $path=Join-Path $repoRoot 'broadcast\ExplorationLifecycle.s.sol\421614\run-latest.json';$broadcast=Get-Content -LiteralPath $path -Raw|ConvertFrom-Json;$records=@();$index=0;foreach($tx in @($broadcast.transactions)){ $hash=[string]$tx.hash;$receipt=Invoke-CastJson @('receipt',$hash,'--rpc-url',$RpcUrl);$blockNumber=Convert-RpcQuantity $receipt.blockNumber;$block=Invoke-CastJson @('block',[string]$blockNumber,'--rpc-url',$RpcUrl);$gas=Convert-RpcQuantity $receipt.gasUsed;$price=Convert-RpcQuantity $receipt.effectiveGasPrice;$records+=[ordered]@{run=$runValue;action="transaction-$index";txHash=$hash;blockNumber=[string]$blockNumber;blockTimestamp=[string](Convert-RpcQuantity $block.timestamp);receiptStatus=[string]$receipt.status;gasUsed=[string]$gas;effectiveGasPriceWei=[string]$price;totalFeeWei=[string]($gas*$price);l2FeeComponents=$null;explorerUrl="https://sepolia.arbiscan.io/tx/$hash"};$index++};return $records }

$runs=@();for($run=1;$run -le $runCount;$run++){ $runNumber=[int]$run;Write-Host "Running Arbitrum Sepolia lifecycle $runNumber of $runCount...";$before=Get-Snapshot "run-$runNumber-before";Invoke-Lifecycle;$after=Get-Snapshot "run-$runNumber-after";if(-not $after.accountingIdentityHolds){throw "Accounting identity failed on run $runNumber."};if([System.Numerics.BigInteger]::Parse($after.principalDebt)-ne 0){throw "Debt was not cleared on run $runNumber."};$runTransactions=@(Get-Records -RunNumber $runNumber);$runs+=[ordered]@{run=$runNumber;before=$before;after=$after;transactions=$runTransactions}}
$result=[ordered]@{schemaVersion=1;network='arbitrum-sepolia';chainId=421614;scenario='baseline-lifecycle';deploymentFile=$DeploymentFile;runs=$runs;limitations=@('l2FeeComponents are not populated by this first recorder; gasUsed and effectiveGasPrice are recorded separately.','Receipt success is not presented as settlement or finality.')};$result|ConvertTo-Json -Depth 16|Set-Content -LiteralPath $outputPath -Encoding utf8;Write-Host "Arbitrum lifecycle evidence written to $outputPath"
